// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnvlz8IQcYzm9Yyvtnq0K9SNNpbdZbbxc',
    appId: '1:276657413094:web:b51f0a03e06504194c5427',
    messagingSenderId: '276657413094',
    projectId: 'event-app-67384',
    authDomain: 'event-app-67384.firebaseapp.com',
    storageBucket: 'event-app-67384.appspot.com',
    measurementId: 'G-2CHH6KK70X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFE5vhh9Xsn5_Kd67src1pEsbXSlr0EYk',
    appId: '1:276657413094:android:ea80ea07cb1251124c5427',
    messagingSenderId: '276657413094',
    projectId: 'event-app-67384',
    storageBucket: 'event-app-67384.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB0cZnV6kk1PLriBCU-dbFrWcrCPlMHnE',
    appId: '1:276657413094:ios:1f9d4fd384604c4c4c5427',
    messagingSenderId: '276657413094',
    projectId: 'event-app-67384',
    storageBucket: 'event-app-67384.appspot.com',
    iosBundleId: 'com.example.eventApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB0cZnV6kk1PLriBCU-dbFrWcrCPlMHnE',
    appId: '1:276657413094:ios:f1605441a823d29e4c5427',
    messagingSenderId: '276657413094',
    projectId: 'event-app-67384',
    storageBucket: 'event-app-67384.appspot.com',
    iosBundleId: 'com.example.eventApp.RunnerTests',
  );
}
